Усовершенствование истории работ с задачником
leliaOff/java-kanban pull request #1
Opened 2024-02-19 11:04 UTC by leliaOff

- убрано ограничение на количество задач в истории
- реализована возможность удаления записи из истории по ИД задачи
- реализована уникальность записей в задачнике
- тесты

2024-02-22 18:07 UTC, mikita95 requested changes
Направление верное :) Только нужно реализовать свою версию списка

2024-02-22 18:07 UTC, mikita95 commented on src/kanban/manager/history/InMemoryHistoryManager.java
> +    private final LinkedHashMap<Integer, Task> history;
По заданию нужно реализовать свою версию контейнера, чтобы удаление работало за O(1)

2024-02-27 07:40 UTC, leliaOff commented on src/kanban/manager/history/InMemoryHistoryManager.java
> +    private final LinkedHashMap<Integer, Task> history;
Добрый день
Вернулся проект со страыми замечаниями, хотя я добавила новый коммит после этого коментария 

https://github.com/leliaOff/java-kanban/pull/1/commits/236213dc92ca4de5342a5fcbabed43bf8c833e8c

2024-02-28 05:29 UTC, mikita95 approved these changes
Все отлично:) Можно мержить

2024-02-28 05:29 UTC, mikita95 commented on src/kanban/manager/history/TaskNode.java
> +
Поля должны быть приватными, если это публичный класс, иначе это нарушение инкапсуляции

2024-02-28 05:47 UTC, leliaOff commented on src/kanban/manager/history/TaskNode.java
> +
исправила

2024-02-28 05:48 UTC, merged