Sprint 8 solution time and duration
leliaOff/java-kanban pull request #3
Opened 2024-03-19 14:46 UTC by leliaOff

- добавлена продолжительность и время старта задачи
- добавлен метод вывода задач в порядке приоритета (по времени старта)
- проверка на пересечение по времени
- рефакторинг кода
- тесты

2024-03-20 17:06 UTC, mikita95 requested changes
Все сделано очень хорошо:) Оставил лишь небольшие замечания

2024-03-20 17:06 UTC, mikita95 commented on src/kanban/manager/FileBackedTaskManager.java
> +                    System.out.println("Не удалось сохранить задачу: " + e.getMessage());
Нужно не "прятать" ошибку, а бросать ее дальше, например, используя свое кастомное исключение, так ошибка не потеряется

2024-03-22 06:42 UTC, leliaOff commented on src/kanban/manager/FileBackedTaskManager.java
> +                    System.out.println("Не удалось сохранить задачу: " + e.getMessage());
добавила ManagerRestoreException и ManagerSaveException

2024-03-22 17:03 UTC, mikita95 approved these changes
Все отлично:) Можно мержить пул-реквест

2024-03-23 10:16 UTC, merged